# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7592c0579655b88d0a0bc93efb90270053b04815743eeb47657a7e023cb7fb25b754c422299184e4c3a1e011dea757ac7a9e35986c2c7720a41807da694aace
  doorkeeper:
    name: "oauth_application"
    redirect_uri: "http://localhost:4200/"
test:
  secret_key_base: e8bd7a87364aa33c48ae99669b33c538c1359437a1c45fd67407169ce212428dad777dc70e059e34766f466ffc6d77d32ca9d1b62041dec7a7014bd3375cb8ab
  name: "oauth_application"
  redirect_uri: "http://test:4200/"
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
